### ISSUE TITLE
Error: File to import not found or unreadable: typed. (Rails 7)

### ISSUE THREAD

**Issue by Ouskababoushka** [brandonmcconnell/scss-typewriter#4]
Hello and thank you for your work.
I can't import "typed" in my rails stylesheet application.scss => 'not found or unreadable". Any idea ?

**Comment by brandonmcconnell** [comment]
@Ouskababoushka Did you install the Typed.css package itself? It won't work by simply importing via `@import 'typed';`

I should probably clarify that in the readme, but I believe you'll need to do something like `@import 'some-directory/typed';` replacing `some-directory` with your full path to the directory housing `typed.scss`.

Let me know if that works for you!

**Comment by konung** [comment]
@brandonmcconnell AWEOME Library! So much better than using JS. 🗡️ 😄 

@Ouskababoushka and anyone else using rails 7

It really depends on how your assets pipeline is setup, but since we are talking about just SCSS & no JS, you can simply download raw "`yped.scss` file right here https://github.com/brandonmcconnell/typed.css/blob/master/typed.scss and drop it right next to your `app/assets/stylesheets/application.scss`. Then import it 

```scss
@import "typed";
```

If you wish, you can add a folder inside `app/assets/stylesheets/` like `vendor` or `typed` or some such, and just adjust your import statement accordingly. 
![Screen Shot 2022-10-21 at 18 50 49](https://user-images.githubusercontent.com/72493/197306042-630c6781-d4c3-402f-8b6e-1805b873236a.png)

**Comment by brandonmcconnell** [comment]
Closing this ticket as resolved. @Ouskababoushka please let me know if @konung's suggestion did not resolve your issue.

@konung thanks for the assistance here!
